<template>
  <div
    :class="`absolute bg-gray-800 inset-0 h-screen flex flex-col content-center items-center justify-center loading-stl ${vanish ? '' : 'puff-out-center'}`"
    v-if="loading"
  >
    <atom-spinner :animation-duration="1000" :size="80" color="#02F6B6" />
    <p class="text-gr-green-light">Loading...</p>
  </div>
</template>

<script>
import { AtomSpinner } from 'epic-spinners'

export default {
  components: {
    AtomSpinner
  },
  data: () => ({
    loading: false,
    vanish: true,
    // left: 37, up: 38, right: 39, down: 40,
    // spacebar: 32, pageup: 33, pagedown: 34, end: 35, home: 36
    keys: { 37: 1, 38: 1, 39: 1, 40: 1 }
  }),
  methods: {
    preventDefault(e) {
      e = e || window.event
      if (e.preventDefault) e.preventDefault()
      e.returnValue = false
    },
    preventDefaultForScrollKeys(e) {
      if (this.keys[e.keyCode]) {
        this.preventDefault(e)
        return false
      }
    },
    disableScroll() {
      if (window.addEventListener) {
        // older FF
        window.addEventListener('DOMMouseScroll', this.preventDefault, false)
      }
      document.addEventListener('wheel', this.preventDefault, { passive: false }) // Disable scrolling in Chrome
      window.onwheel = this.preventDefault // modern standard
      window.onmousewheel = document.onmousewheel = this.preventDefault // older browsers, IE
      window.ontouchmove = this.preventDefault // mobile
      document.onkeydown = this.preventDefaultForScrollKeys
    },
    enableScroll() {
      if (window.removeEventListener) {
        window.removeEventListener('DOMMouseScroll', this.preventDefault, false)
      }
      document.removeEventListener('wheel', this.preventDefault, { passive: false }) // Enable scrolling in Chrome
      window.onmousewheel = document.onmousewheel = null
      window.onwheel = null
      window.ontouchmove = null
      document.onkeydown = null
    },
    start() {
      // prevent scrolling
      this.disableScroll()
      this.loading = true
    },
    finish() {
      this.vanish = false
      this.enableScroll()
      setTimeout(() => (this.loading = false), 1500)
    }
  }
}
</script>

<style>
.loading-stl {
  z-index: 99999;
}

.puff-out-center {
  -webkit-animation: puff-out-center 1s cubic-bezier(0.165, 0.84, 0.44, 1) alternate both;
  animation: puff-out-center 1s cubic-bezier(0.165, 0.84, 0.44, 1) alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-9-21 2:43:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation puff-out-center
 * ----------------------------------------
 */
@-webkit-keyframes puff-out-center {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-filter: blur(2px);
    filter: blur(2px);
    opacity: 0;
  }
}
@keyframes puff-out-center {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(2);
    transform: scale(2);
    -webkit-filter: blur(2px);
    filter: blur(2px);
    opacity: 0;
  }
}
</style>
