<template>
  <div
    :class="open? 'absolute bg-gray-800 inset-0 h-screen flex flex-col content-center items-center menu-open' : 'menu-close'"
  >
    <div
      @click="$emit('close', false)"
      class="absolute top-0 right-0 mt-12 mr-12 close-icon cursor-pointer"
    >
      <div></div>
      <div></div>
    </div>
    <ul class="text-6xl w-full text-center my-auto">
      <li class="hover:bg-gray-600 cursor-pointer">The Team</li>
      <li class="hover:bg-gray-600 cursor-pointer">Our Work</li>
      <li class="hover:bg-gray-600 cursor-pointer">Contact</li>
    </ul>
  </div>
</template>

<script>
export default {
  model: {
    prop: 'open',
    event: 'close'
  },
  props: {
    open: Boolean
  }
}
</script>

<style>
.menu-close {
  visibility: hidden;
}

.menu-open {
  visibility: visible;
  animation: scale-in-tr 0.5s cubic-bezier(0.86, 0, 0.07, 1) alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-5 16:54:45
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-tr
 * ----------------------------------------
 */
@keyframes scale-in-tr {
  0% {
    transform: scale(0);
    transform-origin: 100% 0%;
    opacity: 1;
  }
  100% {
    transform: scale(1);
    transform-origin: 100% 0%;
    opacity: 1;
  }
}

/* Close icon style stats here */
.close-icon div {
  display: block;
  height: 3px;
  position: relative;
  transition: transform 0.6s cubic-bezier(0.19, 1, 0.22, 1) 0s, opacity 0.4s cubic-bezier(0.19, 1, 0.22, 1) 0s;
  width: 60px;
}
.close-icon div:first-child {
  transform: translate3d(0px, 10px, 0px) rotate3d(0, 0, 1, -45deg);
}
.close-icon div:first-child::after,
.close-icon div:first-child::before {
  transition: transform 0.6s cubic-bezier(0.19, 1, 0.22, 1) 0s, opacity 0.2s cubic-bezier(0.19, 1, 0.22, 1) 0s;
}
.close-icon div:last-child {
  transform: translate3d(0px, 8px, 0px) rotate3d(0, 0, 1, 45deg);
}
.close-icon div:last-child::after,
.close-icon div:last-child::before {
  transition: transform 0.6s cubic-bezier(0.19, 1, 0.22, 1) 0.2s, opacity 0.2s cubic-bezier(0.19, 1, 0.22, 1) 0.18s;
}
.close-icon div::after,
.close-icon div::before {
  content: '';
  display: block;
  height: 100%;
  pointer-events: none;
  position: absolute;
  width: 100%;
}
.close-icon div::before {
  background: none repeat scroll 0 0 #02f6b6;
  opacity: 1;
  transform: translate3d(0px, 0px, 0px);
}
.close-icon div::after {
  background: none repeat scroll 0 0 #fc8181;
  opacity: 0;
  transform: translate3d(100%, 0px, 0px);
}
.close-icon:hover div::before {
  opacity: 0;
  transform: translate3d(-100%, 0px, 0px);
}
.close-icon:hover div::after {
  opacity: 1;
  transform: translate3d(0px, 0px, 0px);
}

/* close icon style ends here */
</style>
