<template>
  <section
    style="top: 48em;"
    class="w-full flex mx-auto flex-row relative items-center content-around justify-around mt-10 ml-6"
  >
    <div class="h-full box1">
      <h2
        class="font-h font-bold text-5xl z-10 relative mb-3 service-head"
        style="right: 3.7em;"
      >Consultency</h2>
      <img
        width="17%"
        style="top: 1em;"
        class="absolute z-0 opacity-50 mt-16 ml-16"
        src="@/assets/img/slice2-flip.svg"
      />
      <p style="right: -4em;" class="font-sh text-2xl z-10 relative serice-body">
        We help you make sound decisions and evaluate the right solutiion for your business.
        <br />We also provide
        <a class="bg-gr-green-dark">workshops & trainings</a>
      </p>
    </div>
    <div class="h-full box2">
      <h2
        class="font-h font-bold text-5xl relative z-10 mb-3 service-head"
        style="right: 3.6em;"
      >Development</h2>
      <img
        width="17%"
        style="top: 1em;"
        class="absolute z-0 opacity-50 mt-16 ml-16"
        src="@/assets/img/slice1-flip.svg"
      />
      <p style="right: -4em;" class="font-sh text-2xl z-10 relative serice-body">
        We Like to design and create impactful IT solutions.
        <br />You tell us
        <span class="bg-gr-green-dark">your story</span> and we listen.
      </p>
    </div>
    <div class="h-full box3">
      <h2
        class="font-h font-bold text-5xl relative z-10 mb-3 service-head"
        style="right: 3.6em;"
      >Innovation</h2>
      <img
        width="17%"
        style="top: 1em;"
        class="absolute z-0 opacity-50 mt-16 ml-16"
        src="@/assets/img/slice3-flip.svg"
      />
      <p style="right: -4em;" class="font-sh text-2xl z-10 relative serice-body">
        We constantly research and develop solutions for the right use case and market.
        <br />We like to find new ways on how to use
        <span class="bg-gr-green-dark">Blockchain</span>.
      </p>
    </div>
  </section>
</template>

<script>
export default {}
</script>

<style>
.box1 {
  width: 300px;
  height: 300px !important;
}
.box2 {
  width: 300px;
  height: 300px !important;
}
.box3 {
  width: 300px;
  height: 300px !important;
}

.slide-right {
  -webkit-animation: slide-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.slide-left {
  -webkit-animation: slide-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) alternate both;
  animation: slide-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-9-15 2:4:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-right {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 0 !important;
  }
  100% {
    -webkit-transform: translateX(100px);
    transform: translateX(100px);
    opacity: 1 !important;
  }
}
@keyframes slide-right {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 0 !important;
  }
  100% {
    -webkit-transform: translateX(100px);
    transform: translateX(100px);
    opacity: 1 !important;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2019-9-15 1:46:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 0 !important;
  }
  100% {
    -webkit-transform: translateX(-100px);
    transform: translateX(-100px);
    opacity: 1 !important;
  }
}
@keyframes slide-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 0 !important;
  }
  100% {
    -webkit-transform: translateX(-100px);
    transform: translateX(-100px);
    opacity: 1 !important;
  }
}
</style>
