<template>
  <section
    id="scene"
    class="flex flex-col content-center justify-center items-center mt-16"
    style="height: calc(100% - 4rem)"
  >
    <div id="trigger1"></div>
    <div class="mb-6 mt-32 inset-x-auto">
      <div data-dis-container style="height: 33rem;">
        <img
          id="logo"
          data-dis-type="contained"
          data-dis-particle-type="ExplodingParticle"
          src="@/static/pure-logo.png"
          class="w-48 relative left-auto inset-y-auto"
          alt="Logo used in the center of the home page"
        />
      </div>
    </div>
    <div class="inset-x-auto absolute">
      <h1
        class="font-h text-4xl relative"
        id="tagline"
        style="top: 24rem;"
      >Everything begins with an idea.</h1>
    </div>
    <div class data-depth="0.45">
      <img
        style="top: 23rem; transform: scale(1.2, 1.2);"
        src="@/assets/img/forground.png"
        class="w-full relative"
        alt="the forgoround is a picture of a ground covered with leafs"
      />
    </div>
    <div class data-depth="0.5">
      <img
        style="top: 38rem; transform: scale(1.2, 1.2);"
        src="@/assets/img/underground.png"
        class="w-full relative"
        alt="then there is a picture of the underground"
      />
    </div>
  </section>
</template>

<script>
import Parallax from 'parallax-js'
import disintegrate from 'disintegrate'
// import mezr from 'mezr' // TODO: remove unnececary deps
// import _ from 'lodash-es'

export default {
  components: {},
  mounted() {
    /* eslint-disable no-unused-vars, nuxt/no-env-in-hooks */
    // excute deligters
    // prepare parallex scene
    const parallaxScene = document.getElementById('scene')
    const parallaxInstance = new Parallax(parallaxScene)
    // scroll magic
    // init controller
    const ScrollMagic = require('scrollmagic')
    const controller = new ScrollMagic.Controller()
    const scrollScene = new ScrollMagic.Scene({
      triggerElement: '#trigger1',
      duration: 570,
      triggerHook: 0, // don't trigger until #pinned-trigger1 hits the top of the viewport
      reverse: true
    })
      .setPin('#logo')
      .setClassToggle('#tagline', 'text-blur-out') // add class toggle
      .addTo(controller)
    disintegrate.init()
  }
}
</script>

<style>
.debug {
  background-color: red;
  width: 100%;
  height: 2px;
}

#logo {
  pointer-events: all;
}
.scrollmagic-pin-spacer > img {
}
.text-blur-out {
  animation: text-blur-out 1s alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-7 16:39:35
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-blur-out
 * ----------------------------------------
 */
@keyframes text-blur-out {
  0% {
    filter: blur(0.01);
  }
  100% {
    filter: blur(12px) opacity(0%);
  }
}
</style>
